import React from 'react'

export default function About() {
  return (
    <div className="container">
      <h3 className="text-center my-2">About</h3>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima in ipsum impedit sunt blanditiis sequi magni, deleniti, pariatur neque reiciendis eaque eligendi quisquam error accusamus dignissimos dolorum expedita tempora. Sequi ducimus, ipsa nam, vero sit eaque asperiores error veniam quibusdam praesentium fugiat debitis odit eius, blanditiis dolorum cum? Eaque officiis quisquam dolores, ut, ad exercitationem ea eos alias maxime doloribus asperiores laudantium vel minima tenetur iusto soluta qui ratione maiores distinctio libero eum consequuntur harum velit esse? Sint quasi, atque soluta sit iste vitae distinctio velit deserunt tempora incidunt, repellendus, corporis ex vel odit quam rem. Totam corrupti ad dolores? Blanditiis eaque eum minima labore modi, possimus, quam accusantium tempore quia nostrum minus quaerat necessitatibus expedita natus placeat. Quaerat atque hic saepe fugit totam distinctio? Maiores harum modi quam tempora aliquid aut est earum. Id vero nam reiciendis, aperiam perspiciatis fuga neque? Eum qui facilis esse, consequatur, illo excepturi facere quo, est nihil quasi quaerat itaque sint veritatis ducimus eius. Hic modi animi doloribus ut voluptatem eos placeat eius! Repellendus molestias rem officia corporis, earum deserunt culpa voluptates. Voluptatum ea expedita a perspiciatis veniam sequi quisquam nulla officiis corporis, illo tenetur quod illum, laudantium aspernatur recusandae optio ad laboriosam facilis quos! Quas dicta doloribus adipisci iusto deserunt non odit neque voluptatibus quia consequatur exercitationem incidunt, nulla, officia molestias ducimus cum explicabo debitis similique, pariatur deleniti voluptatum. Inventore itaque enim cumque expedita veritatis voluptatem voluptatum maiores, quas a cupiditate, harum commodi accusantium suscipit natus omnis explicabo quam aspernatur, blanditiis mollitia minima. Harum ullam ipsa aspernatur quis eaque dicta ad sed hic ab neque sequi voluptates architecto culpa consequuntur officia perferendis incidunt, ducimus placeat, amet sint, alias mollitia. Sed dignissimos fugiat impedit molestias incidunt ullam assumenda asperiores? Rem repudiandae dolore consectetur, ut doloremque dolores hic inventore nam et at, similique, laborum repellendus!</div>
    </div>
  )
}
